import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import TanStackProvider from "./components/TanStackProvider/TanStackProvider";

const geistInter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TravelTrucks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistInter.variable}>
        <TanStackProvider>
          <Header></Header>
          {children}
        </TanStackProvider>
      </body>
    </html>
  );
}
